#!/usr/bin/env node
import path from "node:path";import {createHash} from "node:crypto";import {access,readFile,readdir,stat} from "node:fs/promises";import {execFileSync} from "node:child_process";
const raw=process.argv.slice(2),i=raw.indexOf("--root"),root=path.resolve(i>=0?raw[i+1]:process.cwd()),full=raw.includes("--full"),checks=[],add=(name,status,detail)=>checks.push({name,status,detail}),exists=async p=>{try{await access(p);return true;}catch{return false;}},hash=v=>createHash("sha256").update(v).digest("hex");
async function tree(p){const es=await readdir(p,{withFileTypes:true}),parts=[];for(const e of es.sort((a,b)=>a.name.localeCompare(b.name))){const t=path.join(p,e.name);parts.push(e.isDirectory()?`${e.name}:${await tree(t)}`:`${e.name}:${hash(await readFile(t))}`);}return hash(parts.join("\n"));}async function hp(p){return (await stat(p)).isDirectory()?tree(p):hash(await readFile(p));}
let config;try{config=JSON.parse(await readFile(path.join(root,".cayos","project.json"),"utf8"));const ok=config.version===1&&config.project?.name&&config.ticketProvider?.type&&config.ticketProvider?.referencePattern&&config.ticketProvider.readOnly===true&&config.codeHost?.type&&config.codeHost.autoMerge===false&&config.verification?.skill&&Array.isArray(config.verification.sourcePaths)&&config.verification.sourcePaths.length;add("project-config",ok?"PASS":"FAIL",ok?"valid contract":"missing/unsafe fields");}catch(e){add("project-config","FAIL",e.code==="ENOENT"?"run /setup-cayos-factory":e.message);}
try{const top=path.resolve(execFileSync("git",["rev-parse","--show-toplevel"],{cwd:root,encoding:"utf8"}).trim());add("git",top===root?"PASS":"FAIL",top===root?"repository root confirmed":`nested inside ${top}`);execFileSync("git",["rev-parse","--git-common-dir"],{cwd:root});add("worktrees","PASS","git common directory available");if(config?.codeHost?.remote)execFileSync("git",["remote","get-url",config.codeHost.remote],{cwd:root});}catch(e){add("git","FAIL",e.message.split("\n")[0]);}
if(config?.verification?.skill){const dir=path.resolve(root,config.verification.skill),file=path.join(dir,"SKILL.md");if(!await exists(file))add("verifier","FAIL",`missing ${config.verification.skill}`);else{const body=await readFile(file,"utf8"),missing=["Launch","Doctor","Drive","Evidence","Cleanup","Helpers"].filter(s=>!new RegExp(`^## ${s}$`,"m").test(body));if(!await exists(path.join(dir,"features","README.md")))missing.push("features/README.md");add("verifier",missing.length?"FAIL":"PASS",missing.length?`missing: ${missing.join(", ")}`:"structural contract satisfied");}}
if(full){const localFile=path.join(root,".cayos","local.json"),lockFile=path.join(root,".cayos","capabilities.lock.json");try{const local=JSON.parse(await readFile(localFile,"utf8")),roles=["orchestrator","implementer","smallReviewer","deepReviewers","repairer","evaluator"],missing=roles.filter(r=>!local.models?.[r]),provider=config.ticketProvider.binding==="cli"?local.ticketProvider?.kind==="cli"&&Array.isArray(local.ticketProvider?.readCommandPatterns)&&local.ticketProvider.readCommandPatterns.length&&local.ticketProvider.readCommandPatterns.every(p=>String(p).startsWith("^")&&String(p).endsWith("$")):local.ticketProvider?.serverName&&Array.isArray(local.ticketProvider?.readTools)&&local.ticketProvider.readTools.length;add("local-bindings",!missing.length&&provider?"PASS":"FAIL",!missing.length&&provider?"models/provider bound":`missing: ${missing.join(", ")||"provider"}`);}catch(e){add("local-bindings","FAIL",e.message);}
  try{const proof=JSON.parse(await readFile(lockFile,"utf8")),projectHash=hash(await readFile(path.join(root,".cayos","project.json"))),localHash=hash(await readFile(localFile)),verifierHash=await tree(path.resolve(root,config.verification.skill)),parts=[];for(const s of config.verification.sourcePaths)parts.push(`${s}:${await hp(path.resolve(root,s))}`);const sourceHash=hash(parts.join("\n")),adapterHash=await hp(path.resolve(root,proof.providerContract.adapter)),evidenceHash=hash(await readFile(path.resolve(root,proof.verifierProof.evidence))),ok=proof.providerContract.status==="PASS"&&proof.providerContract.contractVersion===1&&proof.verifierProof.status==="PASS"&&proof.checkedAt&&proof.projectHash===projectHash&&proof.localHash===localHash&&proof.providerContract.adapterHash===adapterHash&&proof.verifierProof.verifierHash===verifierHash&&proof.verifierProof.sourceHash===sourceHash&&proof.verifierProof.evidenceHash===evidenceHash;add("capability-lock",ok?"PASS":"FAIL",ok?"proofs and hashes match":"proof/hash/evidence mismatch");}catch(e){add("capability-lock","FAIL",`proof path missing or unreadable: ${e.code||e.message}`);}}
const status=checks.some(c=>c.status==="FAIL")?"BLOCKED":checks.some(c=>c.status==="WARN")?"DEGRADED":"READY";console.log(JSON.stringify({status,root,checks},null,2));process.exitCode=status==="BLOCKED"?1:0;
