#!/usr/bin/env node
import path from "node:path";
import { randomUUID } from "node:crypto";
import { existsSync } from "node:fs";
import { readFile, realpath, unlink } from "node:fs/promises";
import { grillDigest, grillGates, validateGrillConverged } from "./grill-transcript.mjs";
import { activeFile,appendJsonl,approvalFor,gitRoot,gitValue,json,runDir,sharedActiveFile,sha256,states,transitions,writeJson } from "./lib.mjs";

const [command,...raw]=process.argv.slice(2); const args={};
for(let i=0;i<raw.length;i++)if(raw[i].startsWith("--")){const key=raw[i].slice(2),next=raw[i+1];args[key]=next&&!next.startsWith("--")?(i++,next):true;}
const root=gitRoot(path.resolve(String(args.root||process.cwd())));
const autoGates=new Set(["sharedUnderstanding","testSeam","ticketPlan","implementation"]);
const gateTarget={sharedUnderstanding:"TEST_SEAM_PENDING",testSeam:"PLAN_PENDING",ticketPlan:"READY_TO_IMPLEMENT",implementation:"IMPLEMENTING"};
const inside=async(target,base)=>{const baseReal=await realpath(path.resolve(base)),resolved=path.resolve(target);let cursor=resolved;while(true){try{const cursorReal=await realpath(cursor),suffix=path.relative(cursor,resolved),targetReal=suffix?path.join(cursorReal,suffix):cursorReal;return targetReal===baseReal||targetReal.startsWith(`${baseReal}${path.sep}`);}catch(error){if(error.code!=="ENOENT")throw error;const parent=path.dirname(cursor);if(parent===cursor)throw new Error("path escapes approved repository");cursor=parent;}}};
async function load(){let active;try{active=await json(activeFile(root));}catch{active=await json(sharedActiveFile(root));}const projectRoot=path.resolve(active.projectRoot||root),dir=runDir(projectRoot,active.runId);return {active,dir,state:await json(path.join(dir,"state.json")),projectRoot};}
const now=()=>new Date().toISOString();
async function applyGateTransition({dir,state,to,gate,proposalHash,evidence,actor}){
  const next={...state,state:to,updatedAt:now(),blockedFrom:to==="BLOCKED"?state.state:(to===state.blockedFrom?null:state.blockedFrom),pendingApproval:gate?null:state.pendingApproval,approvals:gate?{...state.approvals,[gate]:{at:now(),actor,proposalHash,evidence}}:state.approvals};
  await writeJson(path.join(dir,"state.json"),next);await appendJsonl(path.join(dir,"events.jsonl"),{at:now(),type:"state.transitioned",from:state.state,to,actor,reason:String(args.reason||""),approval:gate||null});
  if(["DONE","ABORTED"].includes(to)){try{await unlink(activeFile(root));}catch{}try{await unlink(sharedActiveFile(root));}catch{}}return next;
}

if(command==="init"){
  try{const old=await load();if(!["DONE","ABORTED"].includes(old.state.state))throw new Error(`active run already exists: ${old.active.runId}`);}catch(e){if(String(e.message).startsWith("active run"))throw e;if(e.code&&e.code!=="ENOENT")throw e;}
  const runId=String(args["run-id"]||`${now().replace(/[:.]/g,"-")}-${randomUUID().slice(0,8)}`),head=gitValue(root,["rev-parse","HEAD"],"unborn");
  let configHash="missing";try{configHash=sha256(await readFile(path.join(root,".cayos","project.json")));}catch{}
  const state={version:1,runId,state:"PREFLIGHT",ticketReference:String(args.ticket||""),projectRoot:root,baseHead:head,expectedHead:head,dirtyFingerprint:sha256(gitValue(root,["status","--porcelain=v1","-uall"],"")),configHash,pluginVersion:process.env.CURSOR_PLUGIN_VERSION||"1.1.0",ownedWorktrees:[],autoMode:args.mode==="auto",createdAt:now(),updatedAt:now(),approvals:{}};
  await writeJson(path.join(runDir(root,runId),"state.json"),state);await appendJsonl(path.join(runDir(root,runId),"events.jsonl"),{at:now(),type:"run.initialized",state:"PREFLIGHT"});await writeJson(activeFile(root),{runId,projectRoot:root});await writeJson(sharedActiveFile(root),{runId,projectRoot:root});console.log(JSON.stringify(state,null,2));
}else if(command==="show")console.log(JSON.stringify((await load()).state,null,2));
else if(command==="propose"){
  const {dir,state}=await load(), gate=String(args.gate||""), next={UNDERSTANDING_PENDING:"TEST_SEAM_PENDING",TEST_SEAM_PENDING:"PLAN_PENDING",PLAN_PENDING:"READY_TO_IMPLEMENT",READY_TO_IMPLEMENT:"IMPLEMENTING",READY_FOR_PR:"OPENING_PR"}[state.state],expected=approvalFor[next];
  if(gate!==expected)throw new Error(`state ${state.state} expects proposal gate ${expected||"none"}`);if(!args["proposal-file"])throw new Error("propose requires --proposal-file");
  const proposalHash=sha256(await readFile(path.resolve(String(args["proposal-file"])))),token=randomUUID().replace(/-/g,"").slice(0,8).toUpperCase(),pendingApproval={gate,proposalHash,token,approvalCommand:`/cayos-approve ${gate} ${token}`,registeredAt:now()};
  await writeJson(path.join(dir,"state.json"),{...state,pendingApproval,updatedAt:now()});await appendJsonl(path.join(dir,"events.jsonl"),{at:now(),type:"approval.proposed",gate,proposalHash});console.log(JSON.stringify(pendingApproval,null,2));
}else if(command==="auto-approve"){
  const {dir,state}=await load(),gate=String(args.gate||"");if(!state.autoMode)throw new Error("auto-approve requires auto mode");if(!autoGates.has(gate))throw new Error("gate is not auto-approvable");const to=gateTarget[gate];if(!to)throw new Error(`unknown auto gate: ${gate}`);const allowed=state.state==="BLOCKED"?[state.blockedFrom,"ABORTED"].filter(Boolean):transitions[state.state];if(!allowed.includes(to))throw new Error(`invalid transition: ${state.state} -> ${to}`);const proposalFile=path.resolve(String(args["proposal-file"]||"")),grillFile=path.resolve(String(args["grill-file"]||"")),summaryFile=path.resolve(String(args["summary-file"]||""));if(!(await inside(proposalFile,dir))||!(await inside(grillFile,dir))||!(await inside(summaryFile,dir)))throw new Error("auto-approve paths must stay in active run");const proposalHash=sha256(await readFile(proposalFile));if(state.pendingApproval?.gate!==gate||state.pendingApproval.proposalHash!==proposalHash)throw new Error(`approval proposal was not registered for ${gate}`);const transcript=await json(grillFile);validateGrillConverged(transcript);if(!grillGates(transcript).includes(gate)||transcript.proposalHash!==proposalHash)throw new Error("grill transcript does not match proposal");const cmd=state.pendingApproval.approvalCommand,evidence=sha256(cmd);await appendJsonl(path.join(dir,"user-approvals.jsonl"),{at:now(),promptHash:evidence,approved:true,gate,proposalHash,actor:"auto-grill",grillDigest:grillDigest(transcript)});console.log(JSON.stringify(await applyGateTransition({dir,state,to,gate,proposalHash,evidence,actor:"auto-grill"}),null,2));
}else if(command==="transition"){
  const {dir,state}=await load(),to=String(args.to||"");if(!states.includes(to))throw new Error(`unknown target state: ${to}`);const allowed=state.state==="BLOCKED"?[state.blockedFrom,"ABORTED"].filter(Boolean):transitions[state.state];if(!allowed.includes(to))throw new Error(`invalid transition: ${state.state} -> ${to}`);
  const gate=approvalFor[to];let proposalHash="",evidence="",actor=String(args.actor||"orchestrator");if(gate){if(args.actor==="user"){if(args.approval!==gate)throw new Error(`transition to ${to} requires user approval ${gate}`);proposalHash=sha256(await readFile(path.resolve(String(args["proposal-file"]||""))));evidence=String(args["approval-evidence"]||"");if(state.pendingApproval?.gate!==gate||state.pendingApproval.proposalHash!==proposalHash)throw new Error(`approval proposal was not registered for ${gate}`);let rows=[];try{rows=(await readFile(path.join(dir,"user-approvals.jsonl"),"utf8")).trim().split("\n").filter(Boolean).map(JSON.parse);}catch{}if(!rows.some(r=>r.approved===true&&r.promptHash===evidence&&r.gate===gate&&r.proposalHash===proposalHash))throw new Error(`approval evidence is not a captured user message for ${gate}`);actor="user";}else throw new Error(`transition to ${to} requires user approval ${gate}`);}
  console.log(JSON.stringify(await applyGateTransition({dir,state,to,gate,proposalHash,evidence,actor}),null,2));
}else if(command==="checkpoint"){
  const {dir,state}=await load();if(!String(args.reason||"").trim())throw new Error("checkpoint requires --reason");
  if(args.worktree){const p=path.resolve(String(args.worktree));if(!(state.ownedWorktrees||[]).some(w=>w.path===p))throw new Error(`worktree is not owned by this run: ${p}`);const ownedWorktrees=state.ownedWorktrees.map(w=>w.path===p?{...w,expectedHead:gitValue(p,["rev-parse","HEAD"],""),dirtyFingerprint:sha256(gitValue(p,["status","--porcelain=v1","-uall"],""))}:w);await writeJson(path.join(dir,"state.json"),{...state,ownedWorktrees,updatedAt:now()});console.log(JSON.stringify({checkpointed:p}));}
  else{const next={...state,expectedHead:gitValue(root,["rev-parse","HEAD"],"unborn"),dirtyFingerprint:sha256(gitValue(root,["status","--porcelain=v1","-uall"],"")),ticketRevision:args["ticket-revision"]||state.ticketRevision,ticketSnapshotId:args["snapshot-id"]||state.ticketSnapshotId,updatedAt:now()};await writeJson(path.join(dir,"state.json"),next);console.log(JSON.stringify(next,null,2));}
}else if(command==="register-worktree"){
  const {dir,state}=await load();if(state.state!=="IMPLEMENTING")throw new Error("worktrees may be registered only in IMPLEMENTING");const p=path.resolve(String(args.path||"")),branch=gitValue(p,["rev-parse","--abbrev-ref","HEAD"],""),head=gitValue(p,["rev-parse","HEAD"],"");if(!branch||!head)throw new Error(`invalid worktree: ${p}`);if(gitValue(p,["status","--porcelain=v1","-uall"],""))throw new Error("worktree must be clean when registered");const base=String(args["base-commit"]||state.expectedHead);if(base!==head)throw new Error("registered base commit must equal the clean worktree HEAD");const owned={path:p,branch,baseCommit:base,expectedHead:head,dirtyFingerprint:sha256(""),ticket:String(args.ticket||"")},next={...state,ownedWorktrees:[...(state.ownedWorktrees||[]).filter(w=>w.path!==p),owned],updatedAt:now()};await writeJson(path.join(dir,"state.json"),next);console.log(JSON.stringify(owned,null,2));
}else if(command==="resume"){
  const {state}=await load();let configHash="missing";try{configHash=sha256(await readFile(path.join(root,".cayos","project.json")));}catch{}const checks={projectRoot:root===state.projectRoot,configHash:configHash===state.configHash,expectedHead:gitValue(root,["rev-parse","HEAD"],"unborn")===state.expectedHead,dirtyFingerprint:sha256(gitValue(root,["status","--porcelain=v1","-uall"],""))===state.dirtyFingerprint,pluginVersion:(process.env.CURSOR_PLUGIN_VERSION||"1.1.0")===state.pluginVersion,ticketRevision:!state.ticketRevision||String(args["ticket-revision"]||"")===state.ticketRevision,ownedWorktrees:(state.ownedWorktrees||[]).every(w=>existsSync(w.path)&&gitValue(w.path,["rev-parse","--abbrev-ref","HEAD"],"")===w.branch&&gitValue(w.path,["rev-parse","HEAD"],"")===w.expectedHead&&sha256(gitValue(w.path,["status","--porcelain=v1","-uall"],""))===w.dirtyFingerprint)};const resumable=Object.values(checks).every(Boolean);console.log(JSON.stringify({resumable,state:state.state,checks},null,2));if(!resumable)process.exitCode=2;
}else if(command==="snapshot"){
  const {dir,state}=await load();if(state.state==="PREFLIGHT")throw new Error("snapshots require a resolved ticket");const source=path.resolve(String(args.file||"")),kind=String(args.kind||"ticket");if(!/^[a-z0-9][a-z0-9-]{0,63}$/.test(kind))throw new Error("invalid snapshot kind");const content=await readFile(source),hash=sha256(content),base=path.resolve(dir,"snapshots"),target=path.resolve(base,`${kind}-${hash.slice(0,12)}${path.extname(source)||".json"}`);if(!target.startsWith(`${base}${path.sep}`))throw new Error("snapshot target escapes active run");await writeJson(target,JSON.parse(content));console.log(JSON.stringify({target,sha256:hash}));
}else if(command==="abort"){
  const {dir,state}=await load(),next={...state,state:"ABORTED",updatedAt:now()};await writeJson(path.join(dir,"state.json"),next);try{await unlink(activeFile(root));}catch{}try{await unlink(sharedActiveFile(root));}catch{}console.log(JSON.stringify(next,null,2));
}else throw new Error("usage: run-state.mjs init|show|propose|auto-approve|transition|checkpoint|register-worktree|resume|snapshot|abort");
