#!/usr/bin/env node
import path from "node:path";
import { json,locateActiveRoot,readStdin,runDir } from "./lib.mjs";
const input=await readStdin(),cwd=path.resolve(input.cwd||process.cwd()),active=await locateActiveRoot(cwd);if(!active){console.log(JSON.stringify({permission:"allow"}));process.exit(0);}const state=await json(path.join(runDir(active.root,active.runId),"state.json"));if(["DONE","ABORTED"].includes(state.state)){console.log(JSON.stringify({permission:"allow"}));process.exit(0);}let local={};try{local=await json(path.join(active.root,".cayos","local.json"));}catch{}
const deny=message=>{console.log(JSON.stringify({permission:"deny",user_message:message,agent_message:message}));process.exit(0);},allow=()=>{console.log(JSON.stringify({permission:"allow"}));process.exit(0);};
const command=String(input.command||input.tool_input?.command||""),tool=String(input.tool_name||""),server=String(input.mcp_server_name||""),subagent=String(input.subagent_type||input.agent_name||input.subagent||"");
const implementationAgent=/cayos-(implementer|repairer)/i.test(subagent);
if(/\bgit(?:\s+(?:-C|--git-dir|--work-tree)\s+\S+)*\s+(merge|clean|reset\s+--hard)\b/.test(command)||/\brm\s+(?=[^\n]*?(?:-\w*r\w*|--recursive))(?=[^\n]*?(?:-\w*f\w*|--force))/.test(command))deny("Destructive cleanup and merge are blocked during an active run.");
if(/\bgit(?:\s+(?:-C|--git-dir|--work-tree)\s+\S+)*\s+push\b|\bgh\s+pr\s+create\b/.test(command)&&state.state!=="OPENING_PR")deny(`Push/PR requires OPENING_PR; current state is ${state.state}.`);
if(/\b(?:npm|pnpm|yarn)\s+publish\b|\bgh\s+release\s+create\b|\bvercel\b[^\n]*\s--prod\b|\bkubectl\s+apply\b|\bterraform\s+apply\b|\bdocker\s+push\b/i.test(command))deny("Publication, release, and deployment are outside Cayos authorization.");
const readOnly=["PREFLIGHT","TICKET_RESOLVED","UNDERSTANDING_PENDING","TEST_SEAM_PENDING","PLAN_PENDING","READY_TO_IMPLEMENT","REVIEWING","VERIFYING","READY_FOR_PR","BLOCKED"];
if(/^(Write|Edit|Delete)$/i.test(tool)&&state.state!=="IMPLEMENTING")deny(`Repository writes require IMPLEMENTING; current state is ${state.state}.`);
if(implementationAgent&&state.state==="IMPLEMENTING"&&/^(Read|Write|Edit|Delete|Glob|Grep)$/i.test(tool))allow();
if(command&&readOnly.includes(state.state)){if(/[\r\n;&|`]|\$\(|(?:^|\s)[12]?>/.test(command))deny("Compound commands and redirection are forbidden in read-only stages.");const patterns=Array.isArray(local.ticketProvider?.readCommandPatterns)?local.ticketProvider.readCommandPatterns.map(String):[],provider=patterns.some(s=>{if(!s.startsWith("^")||!s.endsWith("$"))return false;try{return new RegExp(s).test(command.trim());}catch{return false;}}),builtins=[/^\s*(?:git\s+(?:status|diff|log|show|rev-parse|remote|branch\s+--show-current)|rg\b|grep\b|find\b|ls\b|pwd\b|head\b|tail\b|cat\b|sed\s+-n\b)/,/^\s*(?:node|python3)\s+[^\n]*(?:doctor|run-state|discover-project)\.(?:mjs|js|py)\b/,/^\s*(?:npm|pnpm|yarn)\s+(?:run\s+)?(?:test|check|lint|typecheck)\b/,/^\s*node\s+--test\b/].some(r=>r.test(command));if(!provider&&!builtins)deny(`Shell mutation is forbidden in ${state.state}.`);}
const configuredServer=String(local.ticketProvider?.serverName||""),reads=Array.isArray(local.ticketProvider?.readTools)?local.ticketProvider.readTools.map(String):[];if(configuredServer&&server===configuredServer&&!reads.includes(tool))deny(`Provider permits only: ${reads.join(", ")||"none"}.`);
const tokens=tool.replace(/([a-z])([A-Z])/g,"$1_$2").toLowerCase().split(/[^a-z0-9]+/),writes=new Set(["create","update","delete","set","edit","add","remove","archive","comment","assign","label","transition","move","merge","push","send","publish","deploy"]),external=tokens.some(t=>writes.has(t));if(external&&!(/create.*pull.*request|open.*pr/i.test(tool)&&state.state==="OPENING_PR"))deny("External mutations are outside the active stage.");if(/merge/i.test(tool))deny("Automatic merge is forbidden.");allow();
